### PR TITLE
Update build to sbt 1.5.1

### PR DESCRIPTION
**Pull request by custommonkey**

### CODE REVIEW

**Comment by custommonkey** [comment]
Build is failing because sbt-microsites has a dependency on tut which is no longer available. Is sbt-microsites actually being used ATM?

**Comment by juanpedromoreno** [comment]
Thanks @custommonkey for your time! I've just created [this other PR](https://github.com/higherkindness/droste/pull/192), which should fix that problem.

**Comment by juanpedromoreno** [comment]
Just merged it, could you please rebase against `main`? Thanks @custommonkey !

**Review by juanpedromoreno — APPROVED** [review]
Thanks @custommonkey !

**Pull request merged**
